"""

PPDL - Prediksi Pemakaian Daya Listrik
PPDL - Electrical Power Consumption Prediction

Academic Project Title:
Prediksi Pemakaian Daya Listrik Pada Rumah Tangga di Jakarta Berbasis IoT
dengan Menggunakan Metode Fuzzy Time Series

Prediction of Household Electrical Power Consumption in Jakarta
Using the Fuzzy Time Series Method

Property of:
Universitas Trilogi | Teknik Informatika | Program Sarjana (Strata 1)
Trilogi University | Informatics Engineering | Bachelor Degree

Author:
Alma Zannuba Arifah | 19107011

Supervisors:
Ir. Yaddarabulah, M.Kom., Ph.D.
Opitasari, S.Si., M.Kom.

Module:
Logging Event Definitions

Version: 1.0.1
Created: December 2025
"""

"""Catalog event code untuk PPDL LOGGING SPEC V1.1.

Sumber: docs/Doc_for_Ex_Plan-5.md (EVENT CODE - WAJIB).
Tujuan: menyediakan daftar event yang boleh dipakai agar tidak ada EVT liar.
"""

# UI / Workflow / Routing
UI_SELECT_FOLDER = "UI_SELECT_FOLDER"
UI_SELECT_JSON = "UI_SELECT_JSON"
UI_CLICK_IMPORT = "UI_CLICK_IMPORT"
UI_LOAD_DASHBOARD = "UI_LOAD_DASHBOARD"
UI_PLOT_CHART = "UI_PLOT_CHART"
UI_SET_RANGE_AVG = "UI_SET_RANGE_AVG"
UI_SET_RANGE_DAILY = "UI_SET_RANGE_DAILY"
UI_CLICK_START_ANALYSIS = "UI_CLICK_START_ANALYSIS"

# Database / Import
DATA_INGESTION_START = "DATA_INGESTION_START"
DATA_INGESTION_DONE = "DATA_INGESTION_DONE"
DB_INSERT_DONE = "DB_INSERT_DONE"
DB_VALIDATE_SCHEMA = "DB_VALIDATE_SCHEMA"

# HOME (Average/Daily)
HOME_AVG_CALC = "HOME_AVG_CALC"
HOME_DAILY_CALC = "HOME_DAILY_CALC"
HOME_SUMMARY_REFRESH = "HOME_SUMMARY_REFRESH"

# INITIAL (Parameter & Lock)
PARAM_GENERAL_SUBMIT = "PARAM_GENERAL_SUBMIT"
PARAM_FTS_SUBMIT = "PARAM_FTS_SUBMIT"
PARAM_ANN_SUBMIT = "PARAM_ANN_SUBMIT"
PARAM_ARIMA_SUBMIT = "PARAM_ARIMA_SUBMIT"
PARAM_LOCK_APPLIED = "PARAM_LOCK_APPLIED"
PARAM_LOCK_REJECTED = "PARAM_LOCK_REJECTED"

# Preprocess / Common
PRE_RESAMPLE = "PRE_RESAMPLE"
PRE_MISSING_FILL = "PRE_MISSING_FILL"
PRE_SPLIT = "PRE_SPLIT"
ENERGY_CALCULATION = "ENERGY_CALCULATION"

# New Constants per Contract
MODEL_PREP = "MODEL_PREP"
METHOD_FTS = "METHOD_FTS"
METHOD_ANN = "METHOD_ANN"
METHOD_ARIMA = "METHOD_ARIMA"

# Model: FTS
FTS_UOD = "FTS_UOD"
FTS_PARTITION = "FTS_PARTITION"
FTS_FLR = "FTS_FLR"
FTS_FLRG = "FTS_FLRG"
FTS_FORECAST = "FTS_FORECAST"
FTS_METRICS = "FTS_METRICS"

# Model: ANN
ANN_TRAIN_START = "ANN_TRAIN_START"
ANN_TRAIN_END = "ANN_TRAIN_END"
ANN_PREDICT = "ANN_PREDICT"
ANN_METRICS = "ANN_METRICS"

# Model: ARIMA
ARIMA_FIT = "ARIMA_FIT"
ARIMA_DIAG = "ARIMA_DIAG"
ARIMA_FORECAST = "ARIMA_FORECAST"
ARIMA_METRICS = "ARIMA_METRICS"

# Resume / Export
RPT_BUILD_START = "RPT_BUILD_START"
RPT_BUILD_DONE = "RPT_BUILD_DONE"
EXPORT_START = "EXPORT_START"
EXPORT_DONE = "EXPORT_DONE"


ALL_EVENTS: set[str] = {
	UI_SELECT_FOLDER,
	UI_SELECT_JSON,
	UI_CLICK_IMPORT,
	UI_LOAD_DASHBOARD,
	UI_PLOT_CHART,
	UI_SET_RANGE_AVG,
	UI_SET_RANGE_DAILY,
	UI_CLICK_START_ANALYSIS,
	DATA_INGESTION_START,
	DATA_INGESTION_DONE,
	DB_INSERT_DONE,
	DB_VALIDATE_SCHEMA,
	HOME_AVG_CALC,
	HOME_DAILY_CALC,
	HOME_SUMMARY_REFRESH,
	PARAM_GENERAL_SUBMIT,
	PARAM_FTS_SUBMIT,
	PARAM_ANN_SUBMIT,
	PARAM_ARIMA_SUBMIT,
	PARAM_LOCK_APPLIED,
	PARAM_LOCK_REJECTED,
	PRE_RESAMPLE,
	PRE_MISSING_FILL,
	PRE_SPLIT,
	ENERGY_CALCULATION,
	FTS_UOD,
	FTS_PARTITION,
	FTS_FLR,
	FTS_FLRG,
	FTS_FORECAST,
	FTS_METRICS,
	ANN_TRAIN_START,
	ANN_TRAIN_END,
	ANN_PREDICT,
	ANN_METRICS,
	ARIMA_FIT,
	ARIMA_DIAG,
	ARIMA_FORECAST,
	ARIMA_METRICS,
	RPT_BUILD_START,
	RPT_BUILD_DONE,
	EXPORT_START,
	EXPORT_DONE,
	MODEL_PREP,
	METHOD_FTS,
	METHOD_ANN,
	METHOD_ARIMA,
}

